# Generated by Django 5.0.6 on 2024-06-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordkeeper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passwoerd',
            new_name='Password',
        ),
    ]
